# One Page Summary{-}


\begin{itemize}

\item This assessment for `r spp` in Washington waters incorporates a wide range of data sources: removals from two commercial and one recreational fleets; two fishery-dependent indices of abundance, four fishery-independent indices of abundance (including a new nearshore survey), length and conditional age-at-length composition data for several fisheries and surveys; information on weight-at-length, maturity-at-length, and fecundity-at-length; information on natural mortality and the steepness of the Beverton-Holt stock-recruitment relationship; and estimates of ageing error.

\item The major changes from this assessment to the previous one in 2015 are:

- An additional eight years of data and some changes in the estimation of some parameters.
- Change in the removal history, especially the trawl fishery 3A catches from Astoria.
- Breaking the dockside survey into separate private and charter boat surveys. This allowed the ability to exclude years in the charter boat fishery that showed more effects from bag limits.
- Addition of the nearshore survey, and both OCNMS surveys.


\item `r Spp` off the U.S. west coast appear to have complex sex-specific growth and mortality dynamics that are captured in this assessment through sex-specific parameterizations. In particular, observations of older females are lacking in the available data and is addressed by allowing for higher female natural mortality relative to males.

\item The model was highly sensitive to model specifications natural mortality. 

\item The estimated spawning output at the beginning of 2023 was `r ssb_curr` million of eggs (meggs; ~95 percent asymptotic intervals: `r ssb_curr_low` to `r ssb_curr_hi` meggs), which when compared to unfished spawning output (`r ssb0` meggs) gives a relative stock status level of `r round(100*depl_curr,0)` percent (~95 percent asymptotic intervals: `r round(100*depl_curr_low,0)` to `r round(100*depl_curr_hi,0)` percent).  Currently the stock is estimated above the management target of $SO_{40\%}$ in 2023 and is estimated to have reached the target only recently due to several years of above average recruitment. There is more uncertainty in stock size than there is in relative stock status.

\item  Fishing intensity (1 - SPR) has been above the estimated SPR rate fishing intensity target of 0.50 (1 - $\text{SPR}_{50\%}$) since from 1980 until 2019. The spawning output equivalent to 40 percent of the unfished spawning output ($\text{SO}_{40\%}$) calculated using the SPR target ($\text{SPR}_{50\%}$) was `r format(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], digits = 4, scientific = FALSE, big.mark = ',')` meggs. The `r spp` population in Washington at the start of 2023 is estimated to be above the target biomass, and fishing intensity during 2022 is estimated to be below the fishing intensity target. Sustainable total yield, landings plus discards, using $\text{SPR}_{50\%}$ is estimated at `r format(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], digits = 3, scientific = FALSE, big.mark = ',')` mt.   

\end{itemize}

\newpage
