## Fishery-Dependent Data

### Commercial

#### Landings

The systems along the U.S. West Coast for monitoring commercial fishery landings in the past did not keep track of the landings of individual rockfish species, largely because many rockfish species have similar market characteristics and therefore were landed as an unsorted mix of species.  Black rockfish in particular, which are a nearshore species and much less abundant than many of the offshore rockfish species, were generally landed in mixed-species categories.  As a consequence, the historical records do not provide a detailed accounting of the landings of black rockfish.  The basic approach taken to develop the landings series in this assessment (as in past assessments) was to apply values for the proportion of black rockfish sampled in mixed-rockfish landings.  Data on the proportions of black rockfish are sparse, with the consequence that the landings reconstructions are highly uncertain.

Commercial landings data for the modern era (1981 to present) are taken from the Pacific Fishery Information system (PacFIN), which is a central repository for U.S. West Coast groundfish landings and auxiliary information collected by the three state fishery agencies and other agencies.  A description of basic state data collection systems and overview of PacFIN is provided in Sampson and Crone (1997).  Updated dockside sampling protocols and data processing procedures for Washington are described in Tsou et al. [-@tsou_etal_2015] and Tsou and Weyland [-@tsou_weyland_2015].  A variety of sources were used to reconstruct regional landings histories for years earlier than 1981. Comparisons of the commercial catch in each fishery for the current and previous assessments Figure 81.


##### The PacFIN Era: 1981 to 2014

The PacFIN system provides estimates of commercial fishery rockfish landings by species for those strata (year, quarter, port, area, gear type, condition [alive or dead], and market category) that have species composition data available to apportion the landings to species.  For the commercial fisheries in California the source of the information provided to PacFIN is the CalCOM database, which is the repository for commercial groundfish market sample data managed by the California Cooperative Groundfish Survey (Pearson et al. 2008).  In either system, when no species composition data are available, the system reports the landings as the nominal species or as the mixed-species category that it was sold as (e.g., small rockfish), depending on how the landings were originally reported.  The amount of unspecified rockfish that cannot be apportioned to species varies by year, area, and gear type.  In many instances the landings of unspecified rockfish reported by PacFIN are quite substantial.

Although the separate geographic assessments by state region would ideally have strict geographic separation of landed catch to the location of capture, this is not possible to accomplish because information on the fishing location is generally unavailable.  Until recently logbooks that report area of capture were only available for landings by the groundfish trawl fleet.  Oregon has required a logbook for commercial vessels participating in its nearshore fishery since 2004.  At the same nearshore stock assessment workshop [@pfmc_safe_2015] it was agreed that catch histories for black rockfish stocks should be assembled on the basis of port of landing rather than location of fish capture, based on the assumption that neighboring state would catch approximately equal amounts from off each other's waters.  The one exception to this "port-of-landing equals the state-of-capture rule" is for trawl-caught fish landed at Astoria, OR, the vast majority of which were caught in waters off Washington.

Staff from the Oregon Department of Fish and Wildlife (ODFW) used species composition samples collected during 1976 to 1993 to conduct an analysis of the spatial distribution of black rockfish landed at Astoria, OR.  Astoria is the northernmost port in Oregon and is located near the mouth of the Columbia River, which forms the boundary between Oregon and Washington.  The aggregate proportion of black rockfish expanded pounds that were taken north of the Columbia River (i.e., from waters off Washington) was 98.6%.  This percentage was applied to all historical trawl landings of rockfish at Oregon's Columbia River District ports prior to 1976.vNon-trawl landings into Astoria were assumed to have been caught from Oregon waters.  

Starting in 1994 black rockfish landed into Oregon were legally required to be sorted and sold in a separate black rockfish market category and were also reported as separate retained catches in the mandatory trawl logbooks.  Based on the retained catches reported in the logbooks, the estimated proportion of the trawl-caught black rockfish that were caught from off Washington and landed into Astoria ranged from 65 to 100 percent. These black rockfish are accounted for in the Washington regional assessment (Table 48).

The Washington Department of Fish and Wildlife (WDFW) provided commercial fishery landings based on fish ticket records of black rockfish harvested off Oregon by vessels landing at ports in Washington.  Landings were less than 1 mt per year for the period 1971 to 2014; therefore, all landings to Washington ports were assumed to occur in waters off Washington in this assessment.

The landings data series for black rockfish landed in California, Oregon, and Washington during 1981 to 2014 were assembled from three PacFIN or CalCOM data sets.  The first data set consisted of direct estimates of black rockfish landings by state (described as BLCK in PacFIN), which the systems derived from fish tickets, species composition estimates, and trawl-logbooks provided by the California Department of Fish and Wildlife (CDFW), the ODFW, and the Washington Department of Fish and Wildlife (WDFW).  The second data set consisted of landings of black rockfish that were nominally landed in the black rockfish market category (described as BLK1 in PacFIN) but no direct species composition samples were available to confirm their purity.  Prior to 1993, there was no sorting requirement in the states and no explicit market category for black rockfish, which were landed in a mixed-species rockfish category.  Starting in 1994, black rockfish landed in Oregon were legally required to be landed and sorted into a separate black rockfish market category.  Similar sorting requirements were implemented in 2001 in California and in 2006 in Washington.  

The third PacFIN data set (URCK in PacFIN) was derived from landings of rockfish for which species composition sample estimates were unavailable, but which might feasibly contain some black rockfish.  This derivation involved applying estimates of the percentages of black rockfish (%Black) to the landings of unspecified rockfish.

For each regional assessment the final values for annual commercial landings of black rockfish were the sum of the original PacFIN estimates, to which were added the nominal landings of black rockfish (listed as black rockfish on fish tickets but not verified by sampling) and the estimates of black rockfish in the unspecified rockfish landings.

The landings series during the PacFIN era are quite erratic, sometimes exhibiting large variations between years.  While these changes could be a true reflection of changing fishing patterns, they may be no more than artifacts of low levels of species composition sampling.  A study of the groundfish landings estimates for California [@pearson_etal_2008] evaluated the reliability of species composition sampling for various rockfish species.  The study noted that black rockfish are readily misidentified as blue rockfish, that the hook-and-line fishery in California was not well sampled until the 1990s, and that many of the California landings estimates are based on "borrowed" data or by treating the black rockfish market category as "pure".


##### Oregon Commercial Fishery Landings: 1892 to 2014 

The commercial fishery landings data series for Oregon (Table 25) were assembled from four primary sources: 1) PacFIN, as described above; 2) Pacific Marine Fisheries Commission (PMFC) landings data series for 1956 to 1980; 3)Fishery Statistics of the U.S. for 1927 to 1955; and (4) ODFW's Ocean Recreational Boat Survey for 1979 to 2014 (provided by P. Mirick, ODFW).  Details regarding the PMFC and Fishery Statistics of the U.S. data series are provided in the 2007 assessment document.

Much of the information underlying the commercial catch reconstruction was assembled from primary sources described above in a database documented in Karnowski et al. [-@karnowski_historical_2014]. Careful review of the Karnowski et al. database uncovered some unusual features in the species composition information that underlies the landings reconstruction. For example, during the period 1963 to 1975 the annual %Black values used in the Karnowski et al. [-@karnowski_historical_2014] database varied from 0% to 100%, and produced very erratic year-to-year variations in the landings of black rockfish. 

Staff from ODFW recommended using an alternative reconstruction of historic landings that was based on a fixed set of PMFC-area specific %Black values for the time period 1949 to 1975 (2.2% for area 2A, 4.5% for 2B, 4.4% for 2C, and 14.1% for 3A). There were similar issues with high variability in the %Black values used in the Karnowski et al. database for the period 1976 to 1986. For this period staff from ODFW recommended an alternative reconstruction of historic landings based on the following fixed set of PMFC-area specific %Black values: 0.77% for area 2A, 0.29% for 2B, 0.54% for 2C, and 6.82% for 3A.


##### Washington Commercial Fishery Landings: 1940 to 2014

Commercial fishery landings of black rockfish in Washington are compiled from a variety of sources including PacFIN, agency reports, historical fish ticket information and communication with agency personnel (Table 48).  Since 1935, commercial fishing vessels have been required to submit a fish receiving ticket ("fish ticket") for each landing.  Rockfish landings from domestic fishers are usually reported in mixed-species market categories, and are routinely sampled for species composition by port samplers.  The information required on the ticket and sampling methods have changed through time. Due to these changes, we separated the data into three time periods 1935-1969, 1970-1980, and 1981-present based on the level of detail available in the data for compiling landing history in Washington for this assessment.


##### Years 1935 to 1969

Although the original paper fish tickets are no longer available for this period, WDFW recently digitized the daily aggregated data from printed reports, to assist in reconstructing the commercial groundfish fishery landings history for Washington.  These daily aggregated data reports contain summaries of daily catches for port-groups by gear and area fished.  The data are available for 1935 and for 1949-1969, and were used as the basis for the black rockfish catch reconstruction for this time period. 

During this period, mixed-species, nominal market categories were typically used for reporting of the aggregated data.  Market categories such as "red rockfish", "black rockfish" (BLK1), and "unidentified rockfish" (URCK) are typical on fish tickets during this time, lumping all red colored fish and black colored fish into these categories for reporting.  For bottom trawl gears, the BLK1 market category consisted of mostly yellowtail rockfish and silvergrey rockfish (Greg Lippert, pers. comm.).  To split the black rockfish landings out of the BLK1 market category, we assumed 10% of the BLK1 landings were S. melanops (BLCK). We further assumed that no other nominal market categories in the trawl fishery contained S. melanops (see table below). 

For the commercial jig and troll fisheries, rockfish were landed in the unidentified rockfish (URCK) market category.  No species composition samples are available during this time, so we assumed 85% of URCK landings were S. melanops, which matches the species composition data from the 1985-1989 commercial jig fishery.  These estimates were also supported by interviews with port samplers active during portions of this period.  The rockfish caught by troll gears composed of mostly yellowtail and black rockfishes.  Wright [-@wright_1967] reported rockfish species composition of the troll landings by port.  We assumed 80% of URCK caught off central Washington were BLCK and 20% for northern Washington landings.  


#####  Years 1970 to 1980

Original fish ticket data were used for commercial catch estimate during this period.  Fishing areas were better defined and reported during this period; there were no longer interstate areas due to the introduction of current management areas, with a boundary line at the OR/WA state border.  However, issues with URCK market category remained.  Species composition sampling of URCK were conducted for trawl and jig fisheries but not for salmon troll and the "other gears" gear types. 

To estimate the trawl landings of black rockfish in the category URCK, we applied the current WDFW species composition algorithm by gear, port, and quarter.  If no species composition samples were taken during a quarter, we first borrowed annual composition data for the gear/port group.  If those data were not available, a coastwide annual composition for the particular gear type was applied.  There was no borrowing of composition information across gear groups or years.

The commercial jig fleet operates in nearshore waters and black rockfish is the dominant component of the URCK landing for this gear type.  Species composition sampling was not conducted during the 1970-1980 time period.  Based on the samples collected in the 1980s, we assumed that black rockfish made up 80% of the total rockfish landed by the jig fleet.  For the troll fishery, the same proportions as for the pre-1970 time period were applied.

Rockfish (URCK) were also landed in small amounts by other commercial fleets, such as fixed gears and salmon troll.  The fleets in the 70s and 80s predominantly targeted sablefish and halibut in waters too deep for black rockfish.  Port samplers did not recall observing any black rockfish in the fixed gear landings (James Beam and Greg Lippert, pers. comm.).  Therefore, we assumed fixed gear landings were negligible.  For URCK landed by the salmon troll fleet, the majority of troll landings was yellowtail rockfish with smaller numbers of widow, canary, and black rockfish (Wendy Beeghley and James Beam, pers. comm.). We assumed that 10% of the troll rockfish landings were black rockfish for 1970-1980.  


##### Years 1981 to the Present (the PacFIN era)

Rockfish landings from this period are pulled from the PacFIN table called VDRFD.  Landings in this table are the products of nominal landings, as well as area and species compositions.  For the remaining URCK in this table, we applied a coastwide annual composition for each gear, as described above.  After this step, there are still small amounts of URCK for trawl and setline gears.  These landings are not included in this assessment. 

For the jig-gear fishery, dockside sampling was conducted by the WDFW Ocean Sampling Program (OSP) during 1985-1991. These species composition data are not available in PacFIN. For landings during 1985-1991 the URCK species compositions were stratified by year and port. For other years, species compositions were stratified by port only.  For jig-caught fish landed into Seattle annual species compositions from Neah Bay were applied (Table 49) because there was no port sampling in Seattle.
The URCK market category was used until 2000, after which it was replaced by the Slope, Shelf, and Nearshore rockfish market categories.  The commercial nearshore fishery was closed in 1999, so starting in 2000 there are negligible black rockfish landings in any market categories. In 2005 mandatory sorting was established for black rockfish, so all black rockfish landed should be recorded on fish tickets in the BLK1 category.

To assign URCK commercial salmon troll landings, we used the same reasoning assumption as applied to earlier periods (see 1970-1980) to assign 10% of the URCK landed in the salmon troll fishery to black rockfish.  After a complete nearshore closure in 1999, black rockfish landings have been negligible.


#### Foreign Fishery Catches of Black Rockfish

Rogers [-@rogers_species_2003] developed catch reconstructions for removals by foreign trawlers operating off the U.S. West Coast during the late 1960s to mid-1970s. Although this study reports that Japanese vessels operating in the Columbia and Eureka statistical areas (Oregon and northern California) caught substantial amounts of black rockfish, with cumulative catches of more than 500 mt over 10 years, it seems very unlikely that foreign vessels could have operated sufficiently close to shore to catch appreciable amounts of black rockfish. This assessment does not include Rogers' estimates of foreign fleet removals of black rockfish. 


### Recreational Removals

Comparisons of the catch in each recreational fishery for the current and previous assessments are in Figure 81 (OR), and Figure 179 (WA).


#### Oregon Ocean Boats: 1973 -2014 

To produce total catch estimates, the Oregon Recreational Boat Survey (ORBS) applies catch rates from a subsample of vessels (from dockside interviews) to total effort counts at fine levels of stratification (e.g., by week, port, fishery, and type of boat).  

For estimates of landings, catch rates are verified by ORBS biologists.  However, estimates of discarded mortality are based on angler-reported data and thus are less certain.  To estimate discard mortality, ORBS first estimates the number of discarded fish (by species), to which it then applies stratified mortality rates based on the depth of capture to account for the depth-dependent mortality rates associated with barotrauma [@pfmc_safe_2014]. Since the greatest source of black rockfish removals has been from landed catch (typically only 1% of removals are from discard mortality), there has been a relatively high degree of certainty in sport fishery removals.

Since 2001, ORBS has produced comprehensive year-round estimates of catch and effort for all developed Oregon ports (which are available from RecFIN).  However, prior to 2001, ORBS sampling was typically only conducted at major ports during the peak months of sport fishing activity, and no estimates of landed catch were made for unsampled ports and times.  Accordingly, ODFW reconstructed historic ORBS estimates of black rockfish to include landed catch from all ports and times (not yet available on RecFIN), as is done in recent years. 

The sport reconstruction addressed four spatial and temporal coverage biases identified during an external review of ORBS by the RecFIN Statistical Subcommittee [@van_voorhees_etal_2000]: 
1 "Major ports" that were sampled each year were not sampled during the winter months
2 "Minor ports" were not sampled at all during some years
3 effort counts for private boats excluded afternoon and night trips
4 undeveloped launch sites were never sampled (e.g., beaches).

The sport reconstruction utilized ratio estimators, based on years with complete sampling, to expand catches from years with partial sampling.  For instance, the contribution of winter catch to total catch during years with complete sampling was used to the expand catches for years with missing winter catch.  Similarly, the contribution of catch from a minor port to that of the major ports during years with complete sampling was used to expand catches of years that the minor port was not sampled.  The reconstructed catch and effort estimates for ocean boats ramp up in a near linear fashion from the beginning of the time series in 1973 to an initial peak in 1984.  Attempts to estimate ocean boat catch prior to 1973 by fitting a linear function to this initial ramp up resulted in negative catch for 1972, therefore the ocean boat fishery was assumed to have started in 1973.  This comports well with anecdotal information on the early years of the ocean boat fishery, but is in contrast to the treatment of shore based and estuary boat fisheries described below. 


#### Oregon Estuary Boats and Shore: 1915-2014

Since ORBS has only produced estimates of catch and effort for the ocean boat fishery, estimates of historic black rockfish removals from the estuary boat and shore fisheries were obtained from MRFSS. 

Both MRFSS and ORBS were similar in that a dockside angler intercept survey component was used to obtain catch rates.  However, MRFSS used a random-digit phone survey to estimate total effort, whereas ORBS used visual counts to estimate private boat effort (i.e., of vessels crossing the ocean bar or trailer counts) and obtained a census of charter effort via logbooks. 

Although MRFSS had comprehensive spatial and temporal coverage, MRFSS estimates were determined to be biased during the same external review that identified ORBS biases [@van_voorhees_etal_2000].

The first bias was inclusion of freshwater fishing trips in effort counts for marine fisheries that caused the estimates of trips by boat (and presumably also shore-based trips) to be overestimated by 17%.  Specifically, trips from zip codes non-adjacent to the ocean were being recorded as marine trips in the phone survey.  Accordingly, the reconstruction applied a scaling factor to both the shore and estuary boat estimates to remove the freshwater bias.

The second MRFSS bias was an area bias for the boat estimates, whereby ocean boat landings were overestimated by 23% which led to an underestimation of landings by estuary boats.  Although MRFSS estimates of boat catch (by boat type) were not stratified by area, the total (coastwide) estimates were partitioned to inland and ocean areas based on ratios observed in the dockside survey (e.g., if 35% of sampled catch was from the ocean, then 35% of total catch was assigned to ocean boats).  

In order for these area-partitioned estimates to be correct, the MRFSS dockside samples would have had to been representative; however, it was determined that MRFSS had oversampled the central and southern parts of Oregon, with a greater proportion of ocean trips, than to the north, with a great proportion of estuary trips.  Accordingly, another scaling factor was applied to the estuary boat estimates to account for this boat area bias (this bias did not affect the estimates for the shore fishery).

In addition to using scaling factors to account for MRFSS biases — note that the two biases nearly cancel each other for estuary boats &mdash  the reconstruction also corrected errors in weights of individual fish that were used to covert estimated number of fish (the measure produced by MRFSS) to metric tons. While there were a few clear errors for black rockfish (e.g., a 962 mm, 14 kg fish), these had far less relative effect on total removals than occurred for kelp greenling (where the erroneous 91 kg fish doubled the removals for the shore mode in 1981).

Finally, the reconstruction extrapolated landings for years — outside the scope of MRFSS coverage (i.e., 1915-1980, 2005-current).   For years prior to 1980, fishing license sales, the only Oregon auxiliary data source found to be directed related to fishing, was used to scale historic black rockfish landings.  This extrapolation based on Oregon fishing license sales followed the same pattern as observed in the California sport fishery reconstruction for the shore and skiff fisheries [@ralston_documentation_2010].  For missing years during the modern era (2005-present), a simple linear trend of the landings from 1980-2005 was used, which also followed the same trajectory as seen with recent license sales (mostly flat, but slightly decreasing).


#### Washington Sport Fishery Removals: 1940 to 2014

The Washington recreational catch history of black rockfish was reconstructed using several direct and indirect records of black rockfish catch (Table 50). All primary sources report catch in numbers of fish. As sources have been modified and re-evaluated, a completely new catch reconstruction for Washington was developed for this assessment. The following main sources were used in the reconstruction to get numbers of landed black rockfish:

1. Years 1990-2014: Washington Ocean Sampling Program (OSP) boat based angler survey. Monthly catch and effort estimates were based on an expansion procedure that uses a complete count of vessels leaving or entering a port and dockside angler interviews.  Dockside interview collects information on number of anglers, catch area, and target species for all sampled trips.  Shore-based fishing, other than major jetties (e.g., the north jetty at the mouth of the Columbia River), is not sampled and is considered a negligible mode for catching black rockfish in Washington.  Sampling and effort counts occur mainly from April to October.  Winter fishing is also considered negligible. 
2. Years 1967, 1975-1986: Published catch from historical sport catch report series by the Washington Department of Fisheries.
3. Years 1987-1989: The RecFIN estimates were initially considered to supplement these missing years, but the reported values of numbers or black rockfish caught were half the numbers reported in the adjacent years in the published catch records and the estimated in the OSP. The average value from years 1984-1986 and 1990-1992 were instead used in an interpolation of estimated numbers of black rockfish caught in 1987-1989.
4. Years 1950-1966, 1968-1974: Ratio of total rockfish to salmon catch. Buckley [-@buckley_1965] and WDFW (pers. comm.) reported the number of total rockfish caught relative to the number of salmon. This ratio was used to predict total number of rockfishes for the missing years (Figure 177). Data from Buckley [-@buckley_1965] showed black rockfish comprised approximately 60% of total rockfish landings in 1964 and 1965.  This ratio was applied to the predicted total rockfish estimates to derived black rockfish estimates.
5. Years prior to 1950: The resultant values of estimated black rockfish catches during 1950-1974 were used to predict values before 1950 (Figure 178).  Only year 1949 showed a positive catch estimate, so it was the final year of predicted catch. 

Because the catch was reported in numbers, average weights were used to expand numbers to biomass by year in two ways 

1. Years 1979-2014: Average weights converted from lengths (see Section 2.1.4.4 for source of length-weight relationship) from the OSP database were available (except for 1989, which used the average of years 1980-1989).
2. Years prior to 1979: The value from 1979 was extended backwards to all previous years. 1979 and 1980 values were very different from the rest of the time series (larger sizes), so it was reasoned older years would be more similar to the adjacent years than other, more recent years.
Annual numbers of black rockfish were multiplied by yearly average weights to get the final catch estimates in biomass. Despite this very different approach to catch reconstruction, the final results did not differ greatly from the 2007 assessment (Figure 20).


#### Alternate Historical Catch Series

The exploration of alternative removal histories was limited before, during and after the STAR panel. After consulting with state representatives it was apparent that more formal catch history reconstructions with the intent on characterizing stanzas of catch uncertainty is generally needed to specify alternative catch histories that reflect the underlying uncertainty in the catch reconstructions. Sensitivities to 50% and 150% catch times series, as well as using the former catch history in the Washington model were explore and demonstrated little sensitivity to such changes. More work in the future is thus needed to formalize either alternative catch series or explicitly incorporating catch uncertainty into model specification.


### Estimated Discards

In the previous assessment, commercial discards were not accounted for due to the information provided by the West Coast Groundfish Observer Program (WCGOP) at that time, showing about a 1% discard rate in their survey.  We evaluated the WCGOP estimates of black rockfish discards from 2002-2013, which showed a total of 32.2 mt in estimated discards and total landings of 2042.5 mt coastwide, resulting in a rough discard rate estimate of 1.58%.  This amount of discards was included in the CA HKL non-live fishery landings, going back to 1916, and in the OR HKL non-live fishery landings to 1892. Given the minimal amount of discards, no further depth-dependent mortality estimates were evaluated for Oregon and California and this discard rate was added to the total commercial removals.  Parker et al [-@parker_buoyancy_2006] concluded that semi-pelagic, vertically mobile species, such as black rockfish, show less barotrauma; hence these estimates could be slightly overestimated.  

Estimates from the ORBS program of discards of black rockfish in the Oregon sport fishery, based on data collected by observers on charter boat trips, also indicated low levels of discarding. This assessment assumes a discard rate of 0.9% in the sport landings, which is the average of the RecFIN discard estimates in recent years, and this rate is calculated per year and added to the total.

Washington recreational discard estimates were not available until 2002.  Numbers of discarded-by-depth black rockfish were estimated using the same catch expansion algorithm for landed catch.  Surface release mortalities adopted by the Groundfish Management Team (GMT) in their death-by-depth matrix (11%, 20%, 29%, and 63%) were then applied to the number of release black rockfish for each of 4 release depth bins (0-10 fm, 11-20 fm, 21-30 fm, and >30fm), respectively. Total dead released black rockfish were then summed across each depth bin. The average weights of discards were assumed to be the same as the average weights of landed and multiplied by the number of released dead to get total dead in metric tons.   For pre-2002 release, proportions of releases based on a ratio estimator using 2003-2007 data were applied.  For the split between charter and private vessels, the same algorithm used for splitting retained catch was applied. The overall average discard rate in the recreational fisheries was 1.37%. There was no information on Washington commercial discards, so the rate of 1.37% (same as the historical recreational discards) was also applied to the entire commercial time series. This low rate was similar to discard rates estimated in the other states.


## Size and Age Composition Data

Fish length measurements, primarily from the recreational fishery, are one of the major sources of data for this assessment.  Length composition data from the commercial fisheries in Oregon and California were also included, as were some age composition data from the commercial and recreational fisheries in Oregon.

A large proportion of the length composition data were from the Marine Recreational Fishery Statistics Survey (MRFSS), which is a federally funded program operating since 1980 that collects information on the marine sport fisheries.  The MRFSS program includes an intercept survey in which sport anglers are interviewed as they return from fishing trips, and where samplers can identify and measure the retained catches.  The MRFSS sampling is intended to cover all forms of marine recreational fishing, including shore-based activities from beaches, jetties, and piers.  In contrast the ORBS program that operates only in Oregon interviews and samples anglers operating from boats.  The MRFSS length data, which are housed in the RecFIN database, generally do not indicate the sex of individual fish that were measured.  Similarly, the length data collected by the ORBS program does not generally indicate gender.  In Oregon, a separate and independent sampling program from ORBS, the Marine Non-Salmonid Recreational Fishery Study (MNSRFS), collects length, age and gender data from recreational anglers operating from boats.  The length and age data collected by the MNSRFS program are the only recreational data used in the assessment where gender is recorded.


### Length and Age Sample Sizes

The level of commercial fishery sampling for black rockfish has been erratic, with almost no samples taken in Oregon until the early 1990s (Figure 80).  In California there was a shift from trawl to non-trawl samples, which in part reflects the growing importance of hook-and-line fishing in the nearshore areas and the development of a live-fish fishery.  Sampling of the recreational fisheries in Oregon and California by the MRFSS program has been reasonably consistent except for the hiatus during 1990-92 when the program was not funded.  The standard MRFSS sampling program stopped in 2003 in Oregon and in 2004 in California, around which time the states assumed larger roles in sampling their recreational fisheries.  This resulted in some loss of continuity in the sampling processes.


#### Multinomial Sample Sizes

Initial input values for the multinomial samples sizes determine the relative weights applied in fitting the annual composition data within the set of observations for each fishery.  The initial input values in this assessment were based on the following equation developed by I. Stewart and S. Miller (NWFSC), and presented at the 2006 Stock Assessment Data and Modeling workshop.
Neff = Ntrips + 0.138 * Nfish if Nfish/Ntrips < 44
Neff = 7.06 * Ntrips if Nfish/Ntrips ? 44

Tuning of the assessment model involved multiplying the input sample sizes for each fishery by an adjustment factor to achieve a better balance between how well the model fit the set of composition data and how well it should have fit the data given the sample sizes underlying the data.


#### Length Compositions

The length data for the assessment model were tabulated into 2-cm length bins ranging from 10 cm to 64 cm, with accumulator bins at each end. 

The length composition data indicate some general differences between the three fishery types, with the trawl fisheries producing the largest fish, the recreational fisheries producing the smallest fish, and the non-trawl fisheries producing fish of intermediate length.  There is little evidence in any of the length composition data of distinct modes or successions of modes from one year to the next that might represent strong year-classes.

The recreational fishery length composition data from Oregon are generally quite symmetrically distributed, whereas the recreational fishery length composition data from California are often quite asymmetric, with an extended shoulder having modest numbers of large fish.   However, the data for the first few years of the California series are similar in general shape to the Oregon recreational length composition data.

Sample length composition data from the California sport fishery for 1999 and 2000 were excluded from the assessment model because they had very narrow distributions and were extremely different from adjacent years.  Close examination of the raw data did not indicate any obvious reason for the odd appearance of these length compositions.


##### Oregon Length Compositions

###### Commercial

The biological data for the commercial fishery were extracted from PacFIN on April 24th, 2015.  These data are from trawl and non-trawl (hook-and-line) dead and live-fish fisheries from ports south of Astoria.  The PacFIN dataset contains records for Oregon landings into Astoria; however, these are believed to have been landed in Washington waters and are used in the Washington model.  Length composition data are reported either in fork length or total length (Table 27).  Fork lengths are preferred; where they are missing the total length is used. These data are expanded to reduce the effect of non-uniform sampling effort. The expansions are by weight, catch/sampled catch; first on a per-trip level, and then on a per-year, per-fishery level.  Expansion factors have a minimum value of 1, and are capped at their 90th percentile value. The final sample size is the product of the two expansion factors, which is then capped at its 90th percentile value. The data were stratified by gender and fishery (Table 27).  The final sample sizes were stratified and summed by length bin (10 cm to 60 64 cm bins, 2 cm in width), and an effective sample size is computed from the number of trips and number of fish each stratum represents, according to the Stewart and Miller method for multinomial fishery data (See page 56). A small number of unsexed fish were present in the data; as these did not represent a distinct length distribution, they were excluded from the model.


###### Recreational

Recreational length composition samples for Oregon were obtained and considered from 3 sources: RecFIN, ODFW-ORBS, and independent ODFW length-age sampling.  For 1980-1989 and 1993-2003, the MRFSS program collected unsexed individual fish lengths for all modes (MM, BB, CPFV and PR) from both ocean and inland (estuary) areas. From 1980-1989, MRFSS collected total lengths, but after a hiatus from 1990-1992, the renewed MRFSS program began collecting fork lengths.  RecFIN provides a species-specific total length to fork length conversion, which was used in to standardize all MRFSS length data to fork length.  From 2003-2005, the state managed Shore and Estuary Boat Survey (SEBS) collected fork length data from shore modes in both ocean and inland areas, and from boat modes only in inland areas.  MRFSS/SEBS length data were extracted from RecFIN using the sample data query (http://www.recfin.org/sample-data).  Sample sizes and number of trips by year, and fishery used to generate the effective sample size for inputs are shown in Table 29.

From 2001 through the present, the state managed ORBS program has collected unsexed groundfish fork length data from recreational boats, primarily from ocean fisheries but with a handful of samples from boats fishing in inland waters.  For this assessment, ORBS length data from 2001-2014 were obtained from ODFW (Table 29). Shore based modes are not sampled by ORBS. A comparison of the ORBS and MRFSS data showed a 2 cm different in average lengths, even though the average lengths by year within each data set change little over time. The reason for this difference is not understood. Given both data sets inform one fishery (the recreational ocean fishery), a block in the selectivity parameters was explored to address this issue, but very similar selectivity values were estimated, so the block was not included in the final base model. Therefore, the effect of this difference is very small in the model, though understanding why it exists (and if it exists in other species) should be looked into further.

From 1978 through the present, ODFW has collected sexed black rockfish length composition data from recreational ocean boat fisheries in conjunction with age structure sampling, independent of both the MRFSS/SEBS and ORBS sampling programs.  These collections have been managed under various programs over the years; the current program is known as Marine Non-Salmonid Recreational Fish Studies (MNSRFS), which has existed in its current form since 2005.  Collections from 1978 were only from the port of Brookings, and from 1979-1989 were only from the port of Garibaldi.  Beginning in 1990, geographic representation improved with sampling occurring in Garibaldi, Newport, and Brookings each year.  Beginning in 1994 the port of Charleston was also sampled each year and in 1999, sampling was expanded to include all ports with significant black rockfish landings, although this has been somewhat sporadic in the relatively minor ports (Table X1).  No sampling was conducted in 2008. Due to concerns about spatial coverage and aging error in the early part of this dataset, samples from 1996 onward are used in the model.  Samples from 1996-1998 are included as a "Legacy" dataset.  Composition data were used as collected (i.e., not expanded). Sample sizes per trip for the Effective N calculation were based on unique combinations of Date, Port, BoatName and ReefNumber, as a rough approximation of a trip (Table 29).


##### Washington Length Compositions

###### Commercial

The biological data for the commercial fishery were extracted from PacFIN on April 24th, 2015.  These data are from trawl and non-trawl (hook-and-line) fisheries; there is no live-fish fishery off Washington.  Of 9009 records (each representing a single specimen), 4989 were from the trawl fishery (Table 52).

Length composition data are reported either in fork length or total length.  Fork lengths are preferred; where they are missing the total length is used. These data are expanded to reduce the effect of non-uniform sampling effort (Table 52). The expansions are by weight, catch/sampled catch; first on a per-trip level, and then on a per-year, per-fishery level.  Expansion factors have a minimum value of 1, and are capped at their 90th percentile value. The final sample size is the product of the two expansion factors, which is then capped at its 90th percentile value.  The final sample sizes for the WA biological data ranged from 1 to 389.7, with a median value of 10.4.  

The data were stratified by gender and fishery.  The final sample sizes were stratified and summed by length bin (10 cm to 64 cm bins, 2 cm in width), and an effective sample size is computed from the number of trips and number of fish each stratum represents, according to the Stewart and Miller method for multinomial fishery data. Unsexed fish were treated as above, but entered as a separate dataset.


###### Recreational

The Washington Department of Fish and Wildlife biological database provided sampled length data from the recreational fishery for sexed and unsexed samples for years 1979-2014. Sexed samples were the largest sample sizes and covered most years (Table 53). Composition data were used as collected (i.e., not expanded). Effective sample sizes were based on unique "sequence" sizes, which is roughly equivalent to a trip. 


##### Tagging data

The Washington Department of Fish and Wildlife provided sampled length data from the tagging survey for sexed and unsexed samples for years 1981-2014 (Table 54). Unsexed and sexed data were generally available in different years. Like the recreational data, composition data were used as collected (i.e., not expanded) and effective sample sizes were based on unique "sequence" sizes, which is roughly equivalent to a trip. 


#### Age Compositions

##### Oregon Age Compositions

The fishery data for the assessment model consisted of otolith age-readings, mostly from the recreational fishery (Table 30 to Table 32).  Age composition data were a subset of the length data, 41,212 records in total. The age composition data for the assessment model were tabulated into 1-yr age bins from 1 to 40 years.  For the data tabulation provided in this document, the accumulator bins were extended to compress and simplify display of the data.

The age composition data generally do not show much evidence of distinct year-classes that can be easily tracked from one year to the next, which suggests that that there is not much recruitment variability from year-to-year or that age-reading error is sufficient to mask the appearance of strong year-classes.
As for the length comps, the unsexed fish (139 samples) were treated as a separate dataset.  
Age-at-length compositions were not expanded; the final sample sizes were set to 1 before tallying.  For all three models, the ages were modeled as conditional age-at-length.


##### Washington Age Compositions

Commercial age composition data were a subset of the length data, 7984 records in total, and were expanded in the same manner as the lengths (Table 55).  Ages were stratified by fishery and gender, and binned in 1-year bins from 0 to 45, with additional bins 50 and 55.  As for the length compositions, the unsexed fish (29 samples) were treated as a separate dataset.  Samples were also available by sex for several years in the recreational data (Table 56).

Age-at-length compositions were not expanded; the final sample sizes were the sum of all individual age samples per length bin. For all three models, the ages were modeled as conditional age-at-length.


#### Mean weights


##### Oregon

Although length- or age-compositional data are needed to inform the assessment model about the selection characteristics of the fleets, there are very limited black rockfish compositional data available from the commercial fleets, because the harvests of this species are small compared to harvests of other, more abundant rockfish species.  To supplement the sparse compositional data series from the commercial fleets, series of annual average weight estimates were developed from data on sample weights and numbers of black rockfish, information collected routinely as part of the species composition sampling program in Oregon.  The data indicate substantial differences in mean weight between the trawl and non-trawl fleets, with the trawl fleet landing fish that are about 0.5 kg heavier on average than the fish landed by the non-trawl commercial fisheries (Table 33).


### Abundance Indices

Age and length composition data by themselves do not provide sufficient information to reliably determine trends in stock abundance and biomass.  Most assessments of U.S. West Coast groundfish stocks rely on estimates of stock biomass from research trawl surveys to provide information on biomass trends, but black rockfish are very infrequently caught in any of the bottom trawl surveys, which have a limited coverage of shallow nearshore waters (none of the surveys have ever been conducted in waters shallower than 55 m).  The primary tuning indices available for these assessments are based on recreational catch-per-unit-effort (CPUE), although a series of estimates of absolute abundance, based on an ODFW tagging study, are available for a portion of the stock off Oregon.

The regional assessments for California and Oregon use an approach similar to that used in the 2007 assessment for deriving standardized indices of abundance, and uses the same basic data: dockside interview data from Marine Recreational Fisheries Statistics Survey (MRFSS Type-3 records) in both states, dockside interview data from Ocean Recreational Boat Survey (ORBS) in Oregon; and at-sea observer data from observers aboard commercial passenger fishing vessels (CPFVs) off central California and Oregon.  Dockside interview data are available for Washington from the WDFW OSP.

Given the reliance of all three regional assessments on recreational fishery CPUE data, all three assessments used similar approaches to develop their CPUE indices.  Because sport anglers target a wide variety of species, many fishing trips are very unlikely to ever encounter a black rockfish.  The lack of any catch of black rockfish on these trips provides no information on the relative abundance of black rockfish, and these trips were not included in a catch-rate analysis in these assessments.  

To restrict the sets of ORBS and MRFSS data (respectively) to trips that are likely to have encountered black rockfish, the multispecies analysis developed by Stephens and MacCall [-@stephens_multispecies_2004] was used to select a subset of the data for developing the CPUE indices.  The analysis applies a logistic regression to trip-level data on the presence or absence of the target species (black rockfish) based on presence or absence data for a suite of other species that occur with reasonable frequency in the catch and effort data set.  

The resulting logistic regression coefficients for each of the other species provide a measure of the likelihood of catching the target species, given that the other species were caught.  Positive coefficients imply a greater likelihood of catching the target species.  Separate analyses were done for the dockside MRFSS and ORBS data, and only data from ocean charter boats were used.  Data from private boats were excluded because it seemed likely that private anglers would have less consistent fishing patterns than charter boat operators, and would therefore provide noisier information. A summary of indices considered in each assessment model and general the influence each has on the base models (i.e., rank) is give in Table 5.

#### Oregon On-board Observer Programs

The onboard observer programs in Oregon collect drift-specific information at each fishing stop on an observed trip.  At each fishing stop recorded information includes start and end times, start and end location (latitude/longitude), start and end depth, number of observed anglers (a subset of the total anglers), and the catch (retained and discarded) by species of the observed anglers.  Data for the onboard observer indices used in these black rockfish assessments for the recreational CPFV fleet are from several sampling programs. 

The ODFW initiated an onboard observer program in 2001, which became a yearly sampling program in 2003 (Monk et al. 2013).  Both California and Oregon provided onboard sampling data through 2014.  Data were analyzed at the drift level and catch was taken to be the sum of observed retained and discarded fish.

We created separate indices in California for the 1987-1999 and 2000-2014 datasets due to the number of regulation changes occurring throughout the time period (see Appendix A for regulations history).  In 1987, trips were only observed in Monterey, and are therefore excluded from the analysis. 


##### Data Filtering

Prior to any analyses, preliminary data filters were applied.  Trips/drifts from the CDFW 1988-1998 meeting the following criteria were excluded from analyses:

1.	Drift associated with a fishing location code that was not assigned to a reef.
2.	Drifts identified as having possible erroneous location, observed anglers, or time data
3.	Trips encountering <50% groundfish species.
Trips/drifts from the ODFW, CDFW 1999-2014, and Cal Poly databases meeting the following criteria were excluded from analyses:
1.	ODFW halibut-targeted trips were excluded.
2.	Trips encountering <50% groundfish species. 
3.	Drifts within the current Stonewall Bank Yelloweye Rockfish Conservation Area.
4.	Drifts within Arcata Bay, Humboldt Bay, South Bay, or San Francisco Bay.
5.	Drifts missing a starting location (latitude/longitude).
6.	Drifts identified as having possible erroneous location or time data.
7.	Drifts missing both starting and ending depths.
8.	Drifts within the habitat data occurring farther than 83 m from a reef in Oregon and 34 m in California (see Appendix B for details on reef filtering).
9.	Drifts outside the habitat data in California occurring farther than 141 m from reef (see Appendix B for details on reef filtering).
10.	Drifts occurring on a reef with <3 positive encounters of black rockfish.
11.	Drifts occurring on a reef in which black rockfish was observed in <25% of years the reef was visited.


#### Oregon Commercial Fishery Indices

Only one abundance index is available from the Oregon commercial fisheries, one derived from a nearshore logbook CPUE time-series that was not long enough for use in the 2007 assessment.

##### The Nearshore Logbook Index

The ODFW has required nearshore commercial fishers (both nearshore permitted vessels and open access vessels) to submit fishing logbooks since 2004.  Compliance is generally high, averaging around 80%, but has varied through time ranging from 65% in 2007 to 95% in recent years.  Although required to provide all requested information in the logbook per fishing gear set, there has been substantial variation in the quantity and quality of information reported in logbooks.  Responses from submitted logbooks were entered into a central database and span the years 2004 through 2013.  At the time of this assessment, 2014 logbook submissions were not fully processed and thus were not available.

Logbook information went through several data quality filters to attain the most consistent and representative data set through time to estimate relative abundance trends.  Results from the filtration algorithm are summarized in Table 34. Of note, logbook submissions from black and blue rockfish-permitted vessels with and without a nearshore endorsement were included in the analysis, because these vessels consistently fish in areas where black rockfish are encountered.  

Based on advice from the July STAR panel, a filter that had previously required that a vessel fished in all 10 years (2004-2013) to be included was relaxed to requiring vessels to have fished in only three years to be included.  This increased precision, but did not change the selection of covariates in the final model.  Individual observations of catch (in kg) and effort (hook hour, or the number of hooks used multiplied by the number of hours fished) were at the trip level, where multi-set trips were aggregated to the trip level.  ODFW sets bimonthly trip landing limits for black rockfish and these have changed through time.  However, trip limits have not generally been exceeded in the subset of logbook data used for black rockfish, and thus there was no need to exclude subsequent trips.  The final subset of logbook data included 13,522 trips (60% of the full set of logbook data) from 113 vessels (Figure 84).
Preliminary data analyses identified levels or limits of filtering variables in order to preserve adequate sample sizes and representative trips for black rockfish.  For example, gear type was restricted to hook-and-line (excluding longline gear) because this method accounted for 85% of all sets.  Garibaldi, Pacific City, Port Orford, Gold Beach, and Brookings were the only ports that included a sufficient number of vessels and sets throughout the time series.  Thus, this abundance index is representative of black rockfish in the nearshore in waters adjacent to these locations (Figure 82)
Fishing depth at the start of a set was restricted to within 30 fathoms (54.9 m), which included more than 99% of all sets by permitted vessels, to ensure only CPUE in areas where black rockfish are commonly encountered was evaluated.

Covariates considered in the full model included Month, Vessel, Port, Depth, and People (Figure 85).  All covariates were specified as categorical variables, except depth was a continuous variable.  Depth was included to account for general differences in bathymetry and fishing depth restrictions associated primarily with limiting catch of yelloweye rockfish.  People were included in an attempt to control for the potential oversaturation of hooks at a given fishing location and the interaction that multi-crew trips (# fishers onboard) may have on fishing efficiency.  The selection of covariates included in final models were evaluated using standard information criterion for relative goodness of fit (AICc and BIC) in a backwards stepwise fashion, where a covariate remained in the model if model fit was improved relative to an otherwise identical model without the covariate.   

CPUE was modeled using a delta-GLM approach, where the catch occurrence (binomial) component was modeled using a logit link function and the positive catch component was modeled according to a gamma distribution with a log link function.  CPUE was calculated for each trip, where total catch was defined as the sum total of all reported retained catch (in weight) and released catch (numbers converted to weight by applying a median catch weight) and total effort was defined by hook-hours.  A lognormal distribution for the positive catch component was also evaluated, but graphical summary diagnostics of model adequacy slightly favored the gamma distribution.   A delta-GLMM was also attempted to specify vessel-year interaction effects as stemming from a distribution (random effect) and to account for this added source of variation.  However, the delta-GLM approach was preferred because runtime for the delta-GLMM jackknife procedure to estimate standard errors was restrictive; an alternative normal approximation to the delta-GLMM index standard error estimates resulted in overinflated CVs; and the resulting index time-series between the two approaches was very similar.

Model selection procedures identified the covariates Vessel, Port, and People as important for the catch occurrence (binomial) model component and Vessel, Month, Port, Depth, and People for the positive catch model component.  The categorical Year factor of interest was automatically included in each model component.  Extracted, back-transformed and bias corrected estimates of the Year effect from each model component were then combined and used for the abundance illustrated in Figure 86.  A jackknife resampling routine was conducted to estimate the standard error (and CV) of the Year effects.  The relative effects of each covariate are shown in Figure 87 for the catch occurrence component and Figure 88 for the positive catch component.  Standard model diagnostics show adequate fit and general consistency with GLM model assumptions for the positive catch component (Figure 89).


#### Oregon Recreational Indices

The four recreational fishery abundance indices available for the Oregon regional assessment are summarized in Table 35 and Figure 95.  The sections below describe the underlying data and derivations of the indices.


##### On-Board Observer CPUE for Oregon, 2001 and 2003 to 2014

The filtered dataset included 10,738 drifts, of which 6,410 (60%) drifts with positive encounters.  Only eight samples occurred in the 60-79 m depth range, and we therefore removed drifts from this depth range from the analysis.  ODFW does not sample in Wave 1 (January/February).

The selected data contained categorical variables for Year (13 levels), Wave (4 levels), two Regions (north and south of Florence), and three depth bins (Depth: 0-19 m, 20-39 m, and 40-59 m).  Model selection via AIC selected a lognormal model with Year, Wave, Depth, Region, Depth:Region, and Year:Region, while a binomial with Year, Depth, Region, and Year:Region.  There was enough data to explore a difference in the CPUE trends between regions.  The region south of Florence comprised 72% of the area where black rockfish were encountered, with the remaining 28% north of Florence.  There is no discernable difference, except for 2001, in the indices between the regions (Figure 90).  The trends between the main effects model and the area-weighted mean model are very similar (Figure 90).

In the lognormal submodel, stepwise BIC retained the Year, Depth, Region and the Depth:Region interaction, but did not include any interactions with Year. In the binomial model, stepwise BIC retained Year and Depth. The final Year effects are shown in Table 35 and Figure 95.


##### MRFSS Dockside CPUE for Oregon, 1980 to 2000

For the RecFIN data from Oregon, the logistic regression analysis to select likely black rockfish trips was based on data from 6,165 charter-boat trips and a suite of 23 species (excluding black rockfish).  The analysis generally produced large positive coefficients for shallow-water species that one would expect to co-occur with black rockfish (e.g., copper rockfish and blue rockfish), and large negative coefficients for deep-water or pelagic species that one would not expect to co-occur with black rockfish (e.g., Pacific halibut and coho salmon).  Those trips having an estimated probability of producing a black rockfish that exceeded the cut-off value of 0.758 were selected for the CPUE analysis.  

This cut-off value was chosen to balance the false-positives against the false-negatives and resulted in some trips that were estimated to be false positives, where black rockfish were caught, but should not have been, given the other species caught during those trips.  These probably represent trips that fished in multiple locations, and thus caught a mix of shallow- and deep-water species.  The screening also resulted in the inclusion of trips (false negatives) that should have caught black rockfish (given the other species), but did not.  A total of 5,261 trips were selected for the CPUE analysis.

The MRFSS dockside standardized CPUE index for Oregon (Figure 95) was developed from the selected subset of the catch and effort data using GLMs, with a binomial model to estimate the probability of catching at least one black rockfish and a gamma model to estimate the magnitude of the positive catches per angler-fishing-hour.  In all cases, the structural models had three main effects for the factors Year, Wave (bimonthly period) and Region (southern versus northern OR), and there were no interaction terms.  

The annual index values were derived as the product of two components: predicted values for the probability of catching a black rockfish during a trip, and predicted values for the number of black rockfish caught by an angler per hour of fishing, given that at least one black rockfish was caught.  This CPUE index for Oregon has a high amount of inter-annual variation, particularly in the early part of the time-series.  The index shows a fairly steady upward trend starting from 1987.


##### ORBS Dockside CPUE for Oregon, 2001 to 2014

The ORBS data series for most years does not include full species composition information, and therefore the analysis of these data was restricted to the years 2001-2014, when species composition of the catch is available.  Further, in order to be certain that the characteristics of a trip were comparable, the analysis was restricted to charter boat trips (37,951 records).  The hourly effort associated with these trips can be confounded with travel time, so the travel time was subtracted from the hours fished.  Travel time for charter boats was calculated as 13 mph multiplied by twice the distance between the port of origin and the reef fished (Table 37).  The adjusted hours were multiplied by the number of anglers, and CPUE is expressed in terms of fish per angler-hour.

The species associated with the charter trips were analyzed for inclusion in a Stephens and MacCall [-@stephens_multispecies_2004] logistic regression analysis; "rare species", those occurring in less than 1% of trips, were excluded from consideration as covariates in the analysis.  The regression was run and 21,999 trips predicted to have a likelihood of catching black rockfish above a threshold value of 0.36 were selected as the basis for an index developed in a delta-GLM analysis. Coefficients for predictive species in the analysis are provided in Figure 91.

To develop a standardized CPUE index from the ORBS series, the selected CPUE observations (aggregated catch over aggregated effort) were fitted with a gamma model with main effects for Year, Month, Port, MarBagLim, GF_OpenDepth and ReefFished, with no interactions.  

Model selection based on AIC was used to choose the model with the most support within error distributions (Table 36). AIC was not used to choose between error distributions for the positive catches. This was instead done using quantile-quantile plots (Figure 92 and Figure 93). The full model with lognormal distribution was chosen (Figure 93) and a bootstrap analysis (N=500) was used to estimate the standard errors and CVs of the year effects (Figure 94).


#### Washington Indices

##### Dockside catch-per-unit-effort for Washington

The Washington Department of Fish and Wildlife (WDFW) provided recreational dockside fisheries data from 1981 to 2014. The original data set consisted of 736,271 records, but several data quality filters were used to identify the best subset of the available data to create a representative relative index of abundance (Table 57). The Stephens-MacCall method is an objective approach for identifying trip records of catch and effort data when fishing locations are unknown, based inference regarding the species composition of the catch identifying habitats where the target species is likely to occur (Stephens and MacCall 2004). 

Prior to applying the Stephens-MacCall [-@stephens_multispecies_2004] filter, we identified potentially informative "predictor" species, i.e., those species with sufficient sample sizes and temporal coverage (at least 30 positive trips total, distributed across at least 10 years of the index) to inform the binomial model. Coefficients from the Stephens-MacCall analysis (a binomial GLM) are positive for species which co-occur with black rockfish, and negative for species that are not caught with black rockfish. This filter was performed for years 1981-1989 and 1990-2014 as the recorded species were different in each time series. Species groups are provided in Figure 180 and Figure 181. Black rockfish are extremely common in bottomfish catches, so the Stephens-MacCall filtering method retained a large proportion of the available records (Table 57). 

Catch of black rockfish per angler day was the response variable. Data were collected at the trip level, with the number of landed fish and the number of anglers on each vessel being recorded. The amount of time fished by each angler is not recorded, but was noted to be about 2-3 hours over the time period. This response variable was modeled using a delta-GLM approach, where the catch occurrence (binomial) component was modeled using a logit link function and the positive catch component was modeled using either lognormal or gamma distributions.  

Several covariates were considered in the full model included year, month, boat type, area, daily bag limits and depth restrictions. Depth was not consistently recorded, so depth-based management could not be filtered out. Instead covariates for depth restrictions and daily bag limits were included to represent management changes.  Summer fishing restrictions based on depth limits were implemented during 2006 in WDFW areas 2, 3, and 4. The daily rockfish limit was 15 fish from 1961-1991, 12 fish from 1992-1994, and reduced to 10 fish in 1995. 
Model selection was used to choose the model with the most support within error distributions (Table 58). 

This was done for data sets with and without the Stephens-MacCall filtering method. AIC was not used to choose between error distributions for the positive catches. This was instead done using quantile-quantile plots (Figure 182 to Figure 185). The full model with gamma distribution was chosen for each data set (Figure 186) and a bootstrap analysis (N=500) was used to estimate the standard errors and CVs of the year effects (Figure 187). There is little difference between the filtered-data sets, so the Stephens-MacCall data-set was ultimately used in the base case.

