## Fishery-Independent Data

### Abundance Indices

#### Nearshore Survey CPUE for Washington

Fishery-independent data available for this assessment came from two distinct WDFW research projects. The first was the `r spp` Tagging Program that was initiated in the early 1980s and provided CPUE of `r spp` captured for tag releases primarily off the central coast of Washington. The second data set was from the standardized Coastwide Rod-and-Reel Survey that began in 2019.  While technically independent from one another, these two fishery-independent data sources had comparable components allowing the data to be considered in two different ways. 

The Washington `r spp` Tagging Program was initiated in 1981 with the primary objective of collecting biological information such as growth and movement. The program continued through the 1980’s with modifications to protocols including scope, primary objectives, and tagging methods. Details of this extensive program can be found in @wallace_tag_2010.  Beginning in 1998, the geographic range of sampling was constrained, and effort was primarily focused on rocky habitats during spring months off the central coast of Washington in Marine Catch Area 2 (MCA 2).  Sampling crews consisted of 8-15 anglers using rod-and-reel rigged with one to three single hook jigs per line. During the sampling process, catches of `r spp` per angler minute were recorded, as were covariates month and MCA. `r Spp` were targeted during each trip. In 2010, the WDFW expanded the tagging program to include additional nearshore bottomfish species and increased the geographic disbursement of tags to the entire 180-mile-long Washington coastline. The program retained a primary objective of targeting `r spp` during the spring tagging efforts.

Tag release data collected from the Tagging Program were used for constructing abundance indices in all previous assessments for `r spp` off Washington coast. The 2009 `r spp` Stock Assessment Review (STAR) panel considered tagging catchability (q) as one of the major uncertainties due to the spatial coverage of the tag-release sites focusing mainly on central Washington coastal waters.  The 2015 `r spp` STAR panel recommended future research to include definition and measurement of `r spp` habitat, the development of a coastwide fishery-independent survey for nearshore stocks, and improving CPUE standardization protocols [@brf_STARrev_2015]].

Beginning in 2010, the WDFW started to address STAR panel comments and recommendations. In 2011, geographic coverage of the Tagging Program was expanded by adding more stations to the northern and southern coastal waters, while `r spp` remained the targeted species. In 2014, the WDFW decided to terminate the historical `r spp` Tagging Program and started to plan for a survey to include other nearshore groundfish species besides `r spp`, such as China Rockfish, Quillback Rockfish, Copper Rockfish, Lingcod, Cabezon, and Kelp Greenling.  A series of pilot studies were initiated for site selection, gear testing, and survey timing. The culmination of these efforts from 2014-2018 was the standardized nearshore Coastwide Rod-and-Reel Survey which was initiated in 2019.  Since 2019, the WDFW has conducted an annual spring rod-and-reel survey targeting semi-pelagic bottomfish at 125 fixed stations (e.g., index stations) off the Washington coast.  At each station, 5 anglers deploy standardized fishing rigs consisting of 2 shrimp flies and drift over the rocky habitat 3 times.  Each drift is approximately 8 minutes long.  Details regarding sample frame, site selection, and survey methodology for this survey can be found in the [Groundfish Subcommittee of the Science and Statistical Committee Visual-Hydroacoustic Survey Methodology Review and Hook-and-Line Survey Workshop details from September 2022](https://www.pcouncil.org/documents/2022/10/h-4-a-supplemental-ssc-groundfish-subcommittee-report-2-odfw-video-hydroacoustic-survey-methodology-review-and-wdfw-hook-and-line-survey-workshop-report.pdf/). 

For this assessment abundance indices using data from the two sampling programs described above were evaluated in two ways. First, data from the two projects were evaluated independently. The `r spp` Tagging Program tag release data were filtered for sampling events from 1998-2018 in MCA 2 during the spring months (March-July). This time series had the most consistent survey objectives and sampling protocols during the Program. Because `r spp` were explicitly targeted during these trips, no other filters were applied. Catch of `r spp` per-angler-hour was the response variable, which was an improvement from the past assessment, with covariates year and MCA. CPUE data analysis was done using a hurdle negative binomial regression model.  Figure \ref{fig:tag-index} shows the gamma and hurdle negative binomial model runs with 95% confidence intervals for each year. The standardized nearshore Coastwide Rod-and-Reel Survey data were also analyzed using a hurdle negative binomial regression model for data from years 2019, 2021, and 2022 (Table \ref{tab:nearshore_survey_data}).  Data from 2020 were excluded because only index stations in MCA2 were sampled prior to the survey being cancelled due to the COVID-19 pandemic. Covariates for these analyses included year, MCA, and depth. Table \ref{tab:nearshore_hurdle_modsel} shows the Watanabe-Akaike information criterion (WCIA) used to support the inclusion of year, marine catch area and depth in the final model. The final index is show in Figure \ref{fig:nearshore-index}.

Secondly, data from the two projects were evaluated concurrently.  Because sampling for both projects targeted `r spp` using rod-and-reel methods on rocky habitats, CPUE data for `r spp` was combined.  Data were filtered for sampling only in MCA 2 during spring months.  Additionally, because of changes in survey designs from 2014-2018, only sets that were within 1km of any 1998-2013 central coast Tagging Program set in MCA 2 were included.  The 1km buffer eliminated most sets done on sand or areas that would not have been fished in a tagging objective set. The index calculation did not include a depth covariate as depth was not recorded during the Tagging Program sampling.  Data were analyzed using a hurdle negative binomial regression model for years 1998-2022 (no sampling occurred in MCA 2 in 2008 or 2017). Figure XXX shows the abundance estimates and 95% confidence intervals for each year.

Model runs investigating the sensitivity to independent and combined indices for the fishery-independent research sampling projects were considered. Results of the sensitivity runs found no difference in using one time series or keeping them separate. We choose to keep them separate in the base model as there was a noticeable drop in the transition between the two surveys, thus allowing for a different catchability coefficient to be applied to each time period. It also supports the use of the nearshore survey and it wider coverage to be applied in future assessments. 

#### Olympic Coast National Marine Sanctuary Adult and Young-of-the-Year Surveys

Two surveys conducted between 2015 and 2022 from waters within the Olympic Coast National Marine Sanctuary (OCNMS) were provided for the first time. The adult survey uses SCUBA and belt transects to estimate `r spp` abundance, with fish <10cm considered. Detailed description of survey methods and aims are found in @tolimieri_changes_2023 and in a short description (contained in the supplemental materials on this assessment) provided by Ole Shelton (NWFSC), who kindly provided this data for consideration. The adult survey also supplies coarsely binned length compositions that are used to estimate survey selectivity. The young-of-the-year (YOY) survey is interpreted as an index of recruitment, though admittedly a rough one as it combines Yellowtail Rockfish and `r spp` because they are indistinguishable visually at that size and age. For the purposes of this assessment, these data are included but not expected to provide strong signals. It is more to see if the trends in these data are consistent with the trends in the overall assessment. 
