
### Sensitivity Analyses

Several sensitivity runs were considered for the Oregon model. The first group of sensitivity runs (scenarios 1-6; Table 43; Supplemental table "OR Sensitivities- Like Comps") sequentially removes indices. The second group (scenarios 7-13; Table 43; Supplemental table "OR Sensitivities- Like Comps") sequentially removes length composition data. The third group (scenarios 14-19; Table 43; Supplemental table "OR Sensitivities- Like Comps") sequentially removes indices, size or age composition data. The last group (scenarios 19-33; Table 44; Supplemental table "OR Sensitivities- Model specs") covers a variety of issues: 

1. Estimate M step
2. M step (at age 10) fixed at 2007 values
3. M ramp (at age 10) fixed at 2007 values
4. M estimated, no step
5. M using Then et al. 2015 VBGF calculation; age-based selectivity
6. M based on Then et al. (2015) using amax = 56; age-based selectivity
7. M based on Hamel (2015) using amax = 56; age-based selectivity
8. Estimate female M with male offset set at -0.2
9. Fix tag Q = 12.5%
10. Estimate tag Q
11. Data weighting: length using Francis method; no age weighting
12. Data weighting: lengths and ages using harmonic mean
13. No recruitment estimation
14. No extra variance estimated on all indices 
15. Recreational ocean fishery selectivity logistic

The model was generally insensitive to the removal of indices, except when the tag index was removed as well as the tag Q fixed value. The model was more sensitive to the removal of age compositions, particularly the recreational ocean fishery, resulting mostly in the changes of absolute spawning output. This general insensitivity is due to the fact that tag Q is fixed in the base model. Previous model exploration that did not fix tag Q showed sensitivity to both the length compositions, which favored higher M values, and age compositions, which favored lower M values.

Results of the model specification sensitivity runs demonstrate a strong sensitivity to the scale parameter Q from the tagging data, though selectivity can also change results (Table 44; Figure 153 and Figure 154). The model is very rigid given the fixed value of tag Q. There is very little effect on stock status when changing the parameterization of M, selectivity, data weighting, or the estimation of recruitments (Figure 155 to Figure 158). Only the treatment of the tag Q parameter causes notable results. Because the Oregon model both kills individuals through elevated M values, but also hides the females via dome-shaped selectivity, the biomass unavailable to fishing mortality ("cryptic biomass") was considered for different values of tag Q. Despite very different assumptions of stock scale and status from the different Q parameters (Figure 153 and Figure 154), the cryptic biomass was comparable (Figure 159 to Figure 161). 

Overall, the scale of the population (and thus the resultant OFL at the proxy FMSY value) is the most sensitive derived quantity. Lower natural mortality rates caused big changes in the spawning output. Such lower productivity also caused reduced OFLs. Estimating recruitment and assuming logistic selectivity for the recreational ocean fishery also caused changes in the population scale.

WA:
Several sensitivity runs were considered for the Washington model. The first group of sensitivity runs (scenarios 2-4; Table 65; Supplemental table "WA Sensitivities- Like Comps") sequentially removes indices. The second group (scenarios 5-9; Table 65; Supplemental table "WA Sensitivities- Like Comps") sequentially removes length composition data. The third group (scenarios 10-13; Table 65; Supplemental table "WA Sensitivities- Like Comps") sequentially removes age composition data. The last group (scenarios 14-36: Table 66; Supplemental table "WA Sensitivities- Model specs") covers a variety of issues

1. Estimate growth deviations (1980-2014)
2. Estimate growth blocks (1980-1999; 2000-2014)
3. M ramp in females as in 2007 assessment.
4. Estimate M ramp
5. Fix M to Hamel approach value (0.0964)
6. M from STAR presented base case (based on Then et al. 2015); age-based selectivity
7. M based on Then et al. (2015) using amax = 56; age-based selectivity
8. M based on Hamel (2015) using amax = 56; age-based selectivity
9. Estimate M with dome-shaped, age-based selectivity
10. Estimate M ramp with dome-shaped, age-based selectivity
11. Sexual maturity used in the last assessment (2007)
12. M ramp in females and sexual maturity in 2007
13. Sexual maturity estimated from recent samples (2015)
14. M ramp in females and sexual maturity in 2015
15. Functional maturity using original data set
16. Fecundity is linear with intercept = 0, slope =1.
17. Fecundity from 2007 assessment
18. No recruitment estimation
19. Recruitment estimated all years; ?R tuned
20. Use harmonic mean when tuning length compositions
21. Use harmonic mean when tuning length and conditional age-at-length compositions
22. No extra variance estimated on all indices 
23. Recreational fleet length selectivity is dome-shaped 

Results of the likelihood component sensitivity runs are found in Table 65. The model was most sensitive to the exclusion of the dockside recreational index. It was also sensitive to the removal of all length and age data, and particularly to the recreational age data. 

Results of the model specification sensitivity runs are found in Table 66. The largest sensitivities were found in the treatment of maturity, selectivity and natural mortality. The use of sexual maturity (scenarios 24-27) changed the terminal year scale and status of the stock significantly, making it much less reduced in status, though having a smaller influence on catch at SPR50% (Table 21). Natural mortality scenarios with lower M but age-based selectivity had the biggest effect in spawning output (Figure 225), whereas scenarios with ramping of M caused the biggest changes in (i.e., improving) stock status (Figure 226). Fixing M to low values but not compensating with dome-shaped, age-based selectivity caused the population to crash. Scenarios with ramps in M or M estimated, regardless of selectivity form for females, caused the biggest increases in catch at SPR50%. Recruitment deviations are relatively insensitive to the different natural mortality specifications (Figure 227). Most natural mortality scenarios bring the fishing intensity below the SPR harvest level (Figure 228). 


### Retrospective Analysis

OR: Retrospective runs of for the last 5 years plus and additional retrospective back to 2006 (-8 years, the last year of data available in the previous assessment) were conducted. The Oregon model demonstrates little retrospective patterns in both spawning stock output (Figure 170) and relative spawning stock output (Figure 171). 

WA:Retrospective runs of for the last 5 years plus and additional retrospective back to 2006 (-8 years, the last year of data available in the previous assessment) were conducted. The Washington model demonstrates little retrospective pattern in both spawning stock output (Figure 235) and relative spawning stock output (Figure 236). Both indicate that in general, as data is removed, the stock gains spawning output and the relative stock status increases.


### Likelihood Profiles

OR:
Profiles for natural mortality, steepness, initial recruitment (lnR0), and the ln(tag Q) are shown in Figure 162 to Figure 169. The data in the model strongly support high M values, though fixing the tag Q has removed the sensitivity of the derived quantities to this M values (Figure 162 and Figure 163). Fixing Q also makes all likelihood components support a larger M, whereas when tag Q is estimated, length compositions support higher M values and age composition support lower M values. Profiles over steepness show higher steepness values are most supported and have little influence on the derived quantities (Figure 164). All likelihood components but the abundance indices support higher steepness (Figure 165). The lnR0 parameter is very well defined (Figure 166) and supported consistently by all likelihood components (Figure 167). Higher ln(tag Q values) are most supported by the data, a value very different from the fixed value used in the base model (Figure 168). Derived quantities are very sensitive to the value of this parameter. The ln(tag Q) best supported is most influenced by the age data, with the length data supporting a lower ln(tag Q).

WA:
Likelihood profiles were conducted for sex-specific natural mortality (where males were a fixed offset from females), for population scale (initial recruitment (lnR0)) and stock productivity (steepness (h)). Natural mortality values of females between 0.15 and 0.18 were hard to differentiate in the likelihood value, and did not show much difference is stock scale or status (Figure 229). Overall, derived quantities were very sensitive to natural mortality. The likelihood components degraded most with lower and higher natural mortality values (Figure 230). Age and length likelihood components were opposed in their information on natural mortality. Initial recruitment was well informed, with stock status sensitive to the value of initial recruitment (Figure 231). Values of lnR0 greater than the base case estimate quickly rise to unfished status. Age and length likelihood components were sensitive to the value of lnR0 and opposed each other in the relationship to ln R0 (Figure 232). Regarding steepness, a freely estimated steepness would move towards the high bound (Figure 233). Values below 0.7 were not supported by the data. Derived quantities were fairly insensitive to the value of steepness. Most likelihood components behaved consistently to steepness values, though age compositions were most sensitive to high steepness values while all other components were sensitive to very low steepness values (Figure 234).


### Unresolved Problems and Major Uncertainties
