\clearpage
# Tables

<!-- ======================================================= -->
<!-- ***************     Data      ************************* --> 
<!-- ======================================================= -->


<!---
This tex table does not exist, replacing it with WA_Blck_Removals_All_Years.tex
\include{tex_tables/all_removals.tex}
-->

\include{tex_tables/WA_Removals_all.tex}


\include{tex_tables/WA_Rec_recons.tex}


\include{tex_tables/WA_Blck_Annual_Discards.tex}


\include{tex_tables/WA_Blck_Rec_Length_Sample.tex}


<!---
This tex table does not exist, replacing it with WA_BLCK_Rec_Age_Sample.tex
\include{tex_tables/rec_age_sample.tex}
-->

\include{tex_tables/WA_Blck_Rec_Age_Sample.tex}


\include{tex_tables/WA_Comm_Lt_samps.tex}


\include{tex_tables/WA_Comm_Age_samps.tex}


\include{tex_tables/dockside_samples.tex}


\include{tex_tables/nearshore_hurdle_modsel.tex}


\include{tex_tables/WA_Blck_Nearshore_Survey.tex}


\include{tex_tables/WA_Blck_Survey_Tagging.tex}


<!-- ======================================================= -->
<!-- ***************     Biology   ************************* --> 
<!-- ======================================================= -->

\include{tex_tables/age-error-models.tex}

\include{tex_tables/bio-fxn-maturity.tex}


\newpage

<!-- ======================================================= -->
<!-- ***********   Model Parameters     ******************** --> 
<!-- ======================================================= -->

\include{tex_tables/model_structure.tex}

\pagebreak

```{r, results = 'asis'}

mod_params = model$parameters[, 
                                (names(model$parameters) %in%
                                c("Num","Label","Value","Phase","Min",
                                  "Max","Status","Parm_StDev",
                                  "Pr_type","Prior","Pr_SD"))] 


sci_note <- which(mod_params$Label %in% c("Wtlen_1_Fem_GP_1", "Wtlen_1_Mal_GP_1", "Eggs_scalar_Fem_GP_1"))

mod_params[-sci_note,'Value'] = round(as.numeric(mod_params[-sci_note,'Value']), 3)  

# Combine bounds into one column
mod_params$Min = paste('(', mod_params$Min, ', ', mod_params$Max, ')', sep='')
# Combine prior info to one column
mod_params$PR_type = ifelse(mod_params$Pr_type == 'No_prior' , 'None', paste(mod_params$Pr_type,' (', mod_params$Prior,  ', ', mod_params$Pr_SD, ')', sep = ''))
# Set long value to scientific notation
mod_params[mod_params$Label == "Wtlen_1_Fem_GP_1",3] = format(mod_params[mod_params$Label == "Wtlen_1_Fem_GP_1",3], scientific = TRUE)
mod_params[mod_params$Label == "Wtlen_1_Mal_GP_1",3] = format(as.numeric(mod_params[mod_params$Label == "Wtlen_1_Mal_GP_1",3]), scientific = TRUE)
mod_params[mod_params$Label == "Eggs_scalar_Fem_GP_1",3] = format(as.numeric(mod_params[mod_params$Label == "Eggs_scalar_Fem_GP_1",3]), scientific = TRUE)
mod_params[mod_params$Label == "L_at_Amax_Mal_GP_1",3] = round(as.numeric(mod_params[mod_params$Label == "L_at_Amax_Mal_GP_1",3]), 4)
mod_params[mod_params$Label == "VonBert_K_Mal_GP_1",3] = round(as.numeric(mod_params[mod_params$Label == "VonBert_K_Mal_GP_1",3]), 3)
mod_params[mod_params$Label == "CV_old_Mal_GP_1",3] = round(as.numeric(mod_params[mod_params$Label == "CV_old_Mal_GP_1",3]), 3)
#mod_params[,'Value'] = round(as.numeric(mod_params[,'Value']),3)  
remove <- which(grepl("ForeRecr", mod_params$Label ))
mod_params <- mod_params[-remove, ]
mod_params[,'Parm_StDev'] = round(as.numeric(mod_params[,'Parm_StDev']), 3) 
# Remove the max, prior and prior sd columns
drops = c('Max', 'Prior', 'Pr_type', 'Pr_SD', 'Num')
mod_params = mod_params[, !(names(mod_params) %in% drops)]
rownames(mod_params) = c()
mod_params[,"Label"] = gsub("\\_", " ", mod_params[,"Label"])
mod_params[,"PR_type"] = gsub("\\_", " ", mod_params[,"PR_type"])
mod_params=mod_params[,c(1,2,6,3,4,5,7)]
# Add column names
col_names = c('Parameter',
                         'Value',
                         'SD',
                         'Phase',
                         'Bounds',
                         'Status',
                         'Prior (Exp.Val, SD)')
table_format(x = mod_params,
             caption = "List of parameters used in the base model, including estimated values and standard deviations (SD), estimation phase (negative values not estimated), bounds (minimum and maximum), status (indicates if parameters are near bounds), and prior type information (mean and SD).",
             label = "params",
             align = 'l',
             col_names = col_names,
             longtable = TRUE,
             font_size = 9,
             digits = 3,
             landscape = TRUE,
             custom_width = TRUE,
             col_to_adjust = c(1,7), 
             width = c("7.5cm", "3.5cm"))                         
```

\newpage

<!-- ======================================================= -->
<!-- ***********    Like Contributions  ******************** --> 
<!-- ======================================================= -->

\include{tex_tables/likelihoods.tex}

<!-- ======================================================= -->
<!-- ***********    Reference Point table  ******************** --> 
<!-- ======================================================= -->

<!--
This table is included below and referenced in the management section
\include{tex_tables/e_ReferencePoints.tex}

\newpage

-->


<!-- ======================================================= -->
<!-- ***********       Time Series      ******************** --> 
<!-- ======================================================= -->

\include{tex_tables/TimeSeries.tex}

\newpage

<!-- ======================================================= -->
<!-- ****************     Sensitivities      *************** --> 
<!-- ======================================================= -->

\include{tex_tables/data_sensis.tex}

\include{tex_tables/modspec_LH_sensis.tex}

\include{tex_tables/modspec_RecMisc_sensis.tex}

<!-- ======================================================= -->
<!-- ****************  Retrospectives  ******************* --> 
<!-- ======================================================= -->


\include{tex_tables/RetroMohnsrho.tex}


<!-- ======================================================= -->
<!-- ****************  Management *********** --> 
<!-- ======================================================= -->

\include{tex_tables/ReferencePoints.tex}


\include{tex_tables/project.tex}

\newpage

\include{tex_tables/decision_table.tex}

\clearpage

