\clearpage
# Figures

<!-- ====================================================================== --> 
<!-- ******************************* ES *********************************** --> 
<!-- ====================================================================== --> 


<!-- ====================================================================== --> 
<!-- ******************* Intro section *************************** --> 
<!-- ====================================================================== --> 

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the reference model",
label = 'data-plot')
```

<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_AG_Source_Sex.png"), 
caption = "Observed length-at-age by data source and sex",
label = 'len-age-data-sex')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_AG_Sex_Year.png"), 
caption = "Observed length-at-age by sex and year. Total samples are indicated in parentheses",
label = 'len-age-sex-year')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_VBGF_fit.png"), 
caption = "External fits to the observed length-at-age by sex",
label = 'len-age-fit')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_CV_Sex_plot.png"), 
caption = "Coefficient of variation of length by age by sex. Numbers indicate samples by age and colors indicate sex",
label = 'cv-lt-age')
```	


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Model estimated length-at-age. Shaded area indicates 95 percent distribution of length-at-age around the estimated growth curve",
label = 'len-age-ss')
```


\clearpage


```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Age1_1plots.png"), 
caption = "Ageing bias plots by reader comparisons",
label = 'age-bias_plot')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_Reader_Bias_plot.png"), 
caption = "Estimated bias relationships for each considered matrix. Reader 1 is always considered unbiased. Reader 1a and 1b is an intra-reader comparison. B refers to the bias type and S refers to the imprecision type in the model selection for the ageing error matrix",
label = 'age-error-bias')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "WA_Reader_SD_plot.png"), 
caption = "Ageing error matrix standard deviation (SD) values by comparison. B refers to the bias type and S refers to the imprecision type in the model selection for the ageing error matrix",
label = 'age-error-sd')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Fig1_bio_and_func_color.png"), 
caption = "Biological and functional maturity ogives. Biological maturity ogives are represented by the dashed lines (logistic regression and 95% CI is grey, flexible spline and 95% CI is light green). Functional maturity ogives are represented by the solid lines (logistic regression and 95% CI is grey, flexible spline and 95% CI is light blue)",
label = 'bio-fxn-mat-color')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Fig2_func_samplesize_color.png"), 
caption = "Functional maturity ogives and sample size. Functional maturity ogives are represented by the solid lines (logistic regression and 95% CI is grey, flexible spline and 95% CI is light blue) and sample size is denoted by the size of the bubbles)",
label = 'fxn-spline-mat-color')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of length (cm)",
label = 'maturity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity (kg) as a function of length (cm)",
label = 'fecundity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "LW_WA_State_Source_Sex.png"), 
caption = "Sex-specific length (cm)-weight (kg) data for black rockfish samples by source",
label = 'len-weight-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "LW_lines_States_Sex.png"), 
caption = "Sex-specific length (cm)-weight (kg) estimated power function relationships. Washington state estimate relationships are also provided for comparison",
label = 'len-weight-or-wa')
```


\clearpage



<!-- ====================================================================== --> 
<!-- ******************* Bridge Model ************************************* --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
  filein = file.path(bridge_fig_loc, "WA_SB_comp_plot.png"), 
  caption = "Comparison of spawning output for black rockfish in waters off of Washington between Stock Synthesis versions 3.24 and 3.30. Uncertainty envelops are 95% confidence intervals",
  label = 'ssb_bridge_comps')

``` 
```{r, results = 'asis'}
add_figure(
  filein = file.path(bridge_fig_loc, "WA_Dep_comp_plot.png"), 
  caption = "Comparison of spawning output for black rockfish in waters off of Washington between Stock Synthesis versions 3.24 and 3.30. Uncertainty envelops are 95% confidence intervals",
  label = 'deps_bridge_comps')

``` 

<!-- ====================================================================== -->
<!-- ***********************  Model convergence and Jitters  ************************************ --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(modconv_fig_loc, "jitterplot.png"), 
caption = "Jitter runs for the black rockfish reference model, with jitter run number on the x-axis and -log likelihood value on the y-axis. Blue dot are models that match the likelihood value of the reference model, while red dots deviate from the reference model. All red dots are above the blue dots, indicating no better fit to the reference model was found",
label = 'jitter')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(modconv_fig_loc, "pairs_plot_fast.png"), 
caption = "Pairs plots of the fastest mixing parameters from running 2000 posterior draws (and keep every draw) using the random walk Metropolis algorithm. Parameters that show little to no movement are recommended to be fixed to improve model speed and efficiency",
label = 'pairs_plot_fast')
```
\clearpage


<!-- ====================================================================== -->
<!-- ****************** Fit to the Length Data **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__multi-fleet_comparison.png"), 
caption = "Pearson residuals for each fishing fleet and the MPA survey. Closed bubble are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'lt-pearson-resids')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Trawl.png"), 
caption = "Mean length (cm) index from the commercial trawl fishery with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'trawl-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_NonTRWL.png"), 
caption = "Mean length (cm) index from the commercial non-trawl fishery with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'nontrawl-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Recreational.png"), 
caption = "Mean length (cm) index from the recreational fishery with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'rec-mean-len-fit')
```
```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Tagging.png"), 
caption = "Mean length (cm) index from tagging survey with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'tag-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Nearshore_survey.png"), 
caption = "Mean length (cm) index from the Nearshore survey with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'nearshore-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OCNMS.png"), 
caption = "Mean length (cm) index from the OCNMS adult dive survey with 95 percent confidence intervals based on sample sizes and data weighting",
label = 'ocnms-mean-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length (cm) compositions over all years",
label = 'agg-len-fit')
```

<!-- ====================================================================== -->
<!-- ****************** Fit to the Age Data ******************************* --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_data_weighting_TA1.8_condAgeTrawl.png"), 
caption = "Mean age from conditional age-at-length data for the commercial trawl fishery",
label = 'trawl-mean-caal')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_data_weighting_TA1.8_condAgeNonTRWL.png"), 
caption = "Mean age observations from the conditional age-at-length data from the commercial non-trawl fishery",
label = 'nontrawl-mean-caal')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_data_weighting_TA1.8_condAgeRecreational.png"), 
caption = "Mean age observations from the conditional age-at-length data from the recreational fishery",
label = 'rec-mean-caal')
```

<!-- ====================================================================== -->
<!-- ****************** Fit to the Index*********************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_Charter.png"),
caption = "Fit to the charter fishery index of abundance",
label = 'charter-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_Private_Boat.png"),
caption = "Fit to the private fishery index of abundance",
label = 'private-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_Tagging.png"),
caption = "Fit to the tagging survey index of abundance",
label = 'tag-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_Nearshore_survey.png"),
caption = "Fit to the nearshore survey index of abundance",
label = 'nearshore-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_OCNMS.png"),
caption = "Fit to the OCNMS dive survey index of abundance",
label = 'ocnms-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_OCNMS_YOY.png"),
caption = "Fit to the OCNMS dive survey index of abundance",
label = 'ocnms-yoy-index-fit')
```

<!-- ====================================================================== -->
<!-- ******************     Life history parameters    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Model estimated length-at-age in the beginning of the year. Shaded area indicates 95 percent distribution of length-at-age around the estimated growth curve",
label = 'len-age-ss')
```

<!-- ====================================================================== -->
<!-- ******************     Recruitment    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs3_varcheck.png"), 
caption = "Recruitment deviations variance by year. This plot tracks the information content contained in each recruitment deviation. Values below the red line (assumed recruitment variability) indicates years with more informed recruitment deviations",
label = 'rec-devs-sigmas')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recruit_fit_bias_adjust.png"),
caption = "Recruitment bias adjustment applied in the reference model",
label = 'bias-adj')
```
```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs3_varcheck.png"),
caption = "Recruitment deviations variance check. Low standard deviations indicate years with informative deviations ",
label = 'varcheck')
```

<!-- ====================================================================== -->
<!-- ******************     Selectivity    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "sel01_multiple_fleets_length1.png"),
caption = "Length-based selectivity curves for each fleet and survey",
label = 'fleet_selectivity')
```

<!-- ======================================================= -->  
<!-- ****************** Time Series ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning output (in millions of eggs)",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass (mt)",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning output",
label = 'depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(comp_ass_loc, "compare2_spawnbio_uncertainty.png"), 
caption = "Comparison of the time series of spawning output between the 2015 and 2023 assessment results",
label = 'comp_ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(comp_ass_loc, "compare4_Bratio_uncertainty.png"), 
caption = "Comparison of the time series of relative spawning output between the 2015 and 2023 assessment results",
label = 'comp_depl')
```


<!-- ============================================================================== -->
<!-- ******************      Likelihood Profiles      ***************************** --> 
<!-- ============================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"parameter_panel_SR_LN(R0).png"), 
caption = "Initial recruitment ($lnR_0$) likelihood profile (change in the negative log-likelihood across a range of $ln(R0)$ values) and derived quantities. Red line in the top left figure indicates the significance level in likelihood difference",
label = 'R0-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "piner_panel_SR_LN(R0).png"), 
caption = "Initial recruitment ($ln(R0)$) likelihood profile for each of the likelihood components",
label = 'R0-profile-components')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc,"parameter_panel_SR_BH_steep.png"), 
caption = "Beverton-Holt steepness parameter likelihood profile (change in the negative log-likelihood across a range of steepness values) and derived quantities. Red line in the top left figure indicates the significance level in likelihood difference",
label = 'steepness-profile')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "piner_panel_SR_BH_steep.png"), 
caption = "Beverton-Holt steepness parameter likelihood profile for each of the likelihood components",
label = 'steepness-profile-components')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(likeprof_fig_loc, "M_fm_multilikelihood_profile.png"), 
caption = "Female and male $M$ multi-parameter likelihood profile and derived quantities. Red lines in the top left figure indicate significantly similar values compared to the reference model. Broken and solid lines in the bottom right figure indicate target and limit referene points, respectively",
label = 'M-multiprofile-combo')
```


<!-- ====================================================================== -->
<!-- ******************     Retrospectives    ***************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(retro_loc,  "compare2_spawnbio_uncertainty.png"), 
caption = "Change in the estimate of spawning output when the most recent 10 years of data area removed sequentially",
label = 'retro-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(retro_loc,  "compare4_Bratio_uncertainty.png"),
caption = "Change in the estimate of fraction unfished when the most recent 10 years of data area removed sequentially",
label = 'retro-depl')
```

\newpage

